### ISSUE TITLE
9/29 회의록

### ISSUE THREAD

**Issue by lsjs0706** [fishinSausage/iikh_2024#2]
구현 -김건호, 노단하, 안선우, 엄윤상, 이승준
- Recipe class - 김건호
- Menu class - 노단하
- GroceryList class - 이승준
- Meals class - 엄윤상
- IIKH class - 안선우
* 추가되는 클래스 있을 수 있음
* 코드 주석 작성
* Git 사용 / 카카오톡 공유
PPT 및 레포트 작성 - 차경원
발표 - 이동규

**Comment by fishinSausage** [comment]
readme 에 추가할게요
